name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Selenium Grid with Docker Compose
        run: |
          docker-compose up -d
          echo ">> Selenium Grid is ready."

      - name: Run Tests
        run: mvn test -Dmode=remote

      - name: Upload JSON Test Reports as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: JSON report
          path: target/reports/CucumberTestReport.json

      - name: Upload HTML Test Reports as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: HTML report
          path: target/reports/CucumberTestReport.html

      - name: Cleanup Docker Compose
        if: always()
        run: docker-compose down